[phases.setup]
nixPkgs = ['nodejs_22']

[phases.install]
cmds = ["npm install -g pnpm", "npx pnpm install"]

[phases.build]
cmds = ["npx pnpm build"]

[start]
cmd = "npx pnpm drizzle-kit migrate; npx pnpm start"